// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillMatch.API.Data;

#nullable disable

namespace SkillMatch.API.Migrations
{
    [DbContext(typeof(SkillMatchDbContext))]
    [Migration("20261003134323_AddJobMatchSkills")]
    partial class AddJobMatchSkills
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillMatch.API.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MatchedSkillsCount")
                        .HasColumnType("int");

                    b.Property<int>("MissingSkillsCount")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("JobMatches");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatchSkill", b =>
                {
                    b.Property<int>("JobMatchId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("bit");

                    b.HasKey("JobMatchId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobMatchSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobSkill", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("SkillMatch.API.Models.ResumeSkill", b =>
                {
                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ResumeId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ResumeSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Frontend",
                            Name = "React"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Programming Language",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Programming Language",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Frontend",
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frontend",
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Programming Language",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Backend",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Backend",
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Backend",
                            Name = "REST API"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Database",
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Database",
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Database",
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Database",
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Tools",
                            Name = "Git"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Tools",
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 16,
                            Category = "DevOps",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 17,
                            Category = "DevOps",
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Cloud",
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Cloud",
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Testing",
                            Name = "Unit Testing"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Backend",
                            Name = "JWT"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Frontend",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Frontend",
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Backend",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Programming Language",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Programming Language",
                            Name = "Java"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Testing",
                            Name = "xUnit"
                        },
                        new
                        {
                            Id = 28,
                            Category = "DevOps",
                            Name = "CI/CD"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Database",
                            Name = "Redis"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Backend",
                            Name = "RabbitMQ"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Backend",
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Frontend",
                            Name = "Next.js"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Frontend",
                            Name = "Tailwind CSS"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Backend",
                            Name = "GraphQL"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Tools",
                            Name = "Linux"
                        });
                });

            modelBuilder.Entity("SkillMatch.API.Models.SkillRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearningPriority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillRecommendations");
                });

            modelBuilder.Entity("SkillMatch.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Job", b =>
                {
                    b.HasOne("SkillMatch.API.Models.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatch", b =>
                {
                    b.HasOne("SkillMatch.API.Models.Job", "Job")
                        .WithMany("JobMatches")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.Resume", "Resume")
                        .WithMany("JobMatches")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.User", "User")
                        .WithMany("JobMatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Resume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatchSkill", b =>
                {
                    b.HasOne("SkillMatch.API.Models.JobMatch", "JobMatch")
                        .WithMany("MatchSkills")
                        .HasForeignKey("JobMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("JobMatchSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobMatch");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobSkill", b =>
                {
                    b.HasOne("SkillMatch.API.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Resume", b =>
                {
                    b.HasOne("SkillMatch.API.Models.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillMatch.API.Models.ResumeSkill", b =>
                {
                    b.HasOne("SkillMatch.API.Models.Resume", "Resume")
                        .WithMany("ResumeSkills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("ResumeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.SkillRecommendation", b =>
                {
                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("Recommendations")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Job", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatch", b =>
                {
                    b.Navigation("MatchSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Resume", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("ResumeSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Skill", b =>
                {
                    b.Navigation("JobMatchSkills");

                    b.Navigation("JobSkills");

                    b.Navigation("Recommendations");

                    b.Navigation("ResumeSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.User", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("Jobs");

                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
