// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkillMatch.API.Data;

#nullable disable

namespace SkillMatch.API.Migrations
{
    [DbContext(typeof(SkillMatchDbContext))]
    [Migration("20261003142301_SeedRecommendations")]
    partial class SeedRecommendations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillMatch.API.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<decimal>("MatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("MatchedSkillsCount")
                        .HasColumnType("int");

                    b.Property<int>("MissingSkillsCount")
                        .HasColumnType("int");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ResumeId");

                    b.HasIndex("UserId");

                    b.ToTable("JobMatches");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatchSkill", b =>
                {
                    b.Property<int>("JobMatchId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMatched")
                        .HasColumnType("bit");

                    b.HasKey("JobMatchId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobMatchSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobSkill", b =>
                {
                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Importance")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("JobId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExtractedText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("SkillMatch.API.Models.ResumeSkill", b =>
                {
                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ResumeId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ResumeSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Frontend",
                            Name = "React"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Programming Language",
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Programming Language",
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Frontend",
                            Name = "HTML"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Frontend",
                            Name = "CSS"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Programming Language",
                            Name = "C#"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Backend",
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Backend",
                            Name = "Entity Framework Core"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Backend",
                            Name = "REST API"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Database",
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Database",
                            Name = "MySQL"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Database",
                            Name = "PostgreSQL"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Database",
                            Name = "MongoDB"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Tools",
                            Name = "Git"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Tools",
                            Name = "GitHub"
                        },
                        new
                        {
                            Id = 16,
                            Category = "DevOps",
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 17,
                            Category = "DevOps",
                            Name = "Kubernetes"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Cloud",
                            Name = "Azure"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Cloud",
                            Name = "AWS"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Testing",
                            Name = "Unit Testing"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Backend",
                            Name = "JWT"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Frontend",
                            Name = "Angular"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Frontend",
                            Name = "Vue.js"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Backend",
                            Name = "Node.js"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Programming Language",
                            Name = "Python"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Programming Language",
                            Name = "Java"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Testing",
                            Name = "xUnit"
                        },
                        new
                        {
                            Id = 28,
                            Category = "DevOps",
                            Name = "CI/CD"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Database",
                            Name = "Redis"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Backend",
                            Name = "RabbitMQ"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Backend",
                            Name = ".NET"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Frontend",
                            Name = "Next.js"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Frontend",
                            Name = "Tailwind CSS"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Backend",
                            Name = "GraphQL"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Tools",
                            Name = "Linux"
                        });
                });

            modelBuilder.Entity("SkillMatch.API.Models.SkillRecommendation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LearningPriority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("SkillRecommendations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Practice components, hooks, state, forms, and API integration by shipping one small production-style feature.",
                            LearningPriority = "Medium",
                            SkillId = 1,
                            Title = "Build a React feature"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Review modern syntax, closures, promises, array methods, modules, and browser debugging through short exercises.",
                            LearningPriority = "Medium",
                            SkillId = 2,
                            Title = "Strengthen JavaScript fundamentals"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Add strict types to components and API contracts, then remove unsafe any values and handle nullable data.",
                            LearningPriority = "Medium",
                            SkillId = 3,
                            Title = "Use TypeScript in a real feature"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Build an accessible page using meaningful landmarks, forms, headings, labels, and keyboard-friendly controls.",
                            LearningPriority = "Low",
                            SkillId = 4,
                            Title = "Practice semantic HTML"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Recreate a responsive interface using Grid, Flexbox, custom properties, and mobile-first breakpoints.",
                            LearningPriority = "Low",
                            SkillId = 5,
                            Title = "Improve responsive CSS"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Practice collections, LINQ, async/await, records, nullable reference types, and dependency injection in a small service.",
                            LearningPriority = "Medium",
                            SkillId = 6,
                            Title = "Deepen practical C#"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Create authenticated CRUD endpoints with DTO validation, dependency injection, logging, and consistent error responses.",
                            LearningPriority = "High",
                            SkillId = 7,
                            Title = "Build an ASP.NET Core API"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Build relationships, migrations, projections, and tracked versus no-tracking queries against a relational database.",
                            LearningPriority = "Medium",
                            SkillId = 8,
                            Title = "Model data with EF Core"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Practice resource-oriented routes, status codes, validation, pagination, and clear request and response contracts.",
                            LearningPriority = "Medium",
                            SkillId = 9,
                            Title = "Design a REST API"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Write joins, grouping queries, indexes, and execution-plan checks using a realistic application schema.",
                            LearningPriority = "High",
                            SkillId = 10,
                            Title = "Practice SQL Server querying"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Practice schema design, joins, aggregation, indexing, and connecting MySQL to an application.",
                            LearningPriority = "Medium",
                            SkillId = 11,
                            Title = "Learn MySQL essentials"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Practice data types, joins, indexes, query plans, and application integration with PostgreSQL.",
                            LearningPriority = "Medium",
                            SkillId = 12,
                            Title = "Learn PostgreSQL essentials"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Practice document design, indexes, aggregation pipelines, and choosing when embedding or referencing fits best.",
                            LearningPriority = "Medium",
                            SkillId = 13,
                            Title = "Model data in MongoDB"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Practice feature branches, focused commits, rebasing, conflict resolution, and reviewing diffs before merging.",
                            LearningPriority = "Medium",
                            SkillId = 14,
                            Title = "Use Git with confidence"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Publish a documented project with issues, pull requests, code review, and an automated validation workflow.",
                            LearningPriority = "Low",
                            SkillId = 15,
                            Title = "Create a strong GitHub workflow"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Write a multi-stage Dockerfile, configure environment variables, and run the frontend, API, and database locally.",
                            LearningPriority = "High",
                            SkillId = 16,
                            Title = "Containerize an application"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Deploy a container using Deployments, Services, ConfigMaps, Secrets, health probes, and resource limits.",
                            LearningPriority = "High",
                            SkillId = 17,
                            Title = "Learn Kubernetes fundamentals"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Deploy an ASP.NET Core application and database, configure secrets, logs, health checks, and a repeatable release process.",
                            LearningPriority = "High",
                            SkillId = 18,
                            Title = "Deploy a project to Azure"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Practice hosting an application with managed compute and database services, secure configuration, logging, and cost limits.",
                            LearningPriority = "High",
                            SkillId = 19,
                            Title = "Deploy a project to AWS"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Write focused tests for business rules, edge cases, and failures, then run them automatically before every merge.",
                            LearningPriority = "High",
                            SkillId = 20,
                            Title = "Adopt a unit-testing workflow"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Practice token validation, expiration, authorization policies, secure key configuration, and frontend session handling.",
                            LearningPriority = "High",
                            SkillId = 21,
                            Title = "Implement JWT authentication safely"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Practice standalone components, services, reactive forms, routing, and typed HTTP calls in a small application.",
                            LearningPriority = "Medium",
                            SkillId = 22,
                            Title = "Build an Angular feature"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Practice components, Composition API, reactive state, routing, forms, and API integration.",
                            LearningPriority = "Medium",
                            SkillId = 23,
                            Title = "Build a Vue feature"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Create a validated REST service with async error handling, authentication, persistence, logging, and tests.",
                            LearningPriority = "Medium",
                            SkillId = 24,
                            Title = "Build a Node.js service"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Practice data structures, functions, type hints, virtual environments, testing, and a small API or automation project.",
                            LearningPriority = "Medium",
                            SkillId = 25,
                            Title = "Strengthen practical Python"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Practice collections, streams, exceptions, testing, and dependency injection in a small backend service.",
                            LearningPriority = "Medium",
                            SkillId = 26,
                            Title = "Strengthen practical Java"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Write unit and integration tests using fixtures, assertions, mocks where appropriate, and WebApplicationFactory.",
                            LearningPriority = "High",
                            SkillId = 27,
                            Title = "Test .NET code with xUnit"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Automate restore, lint, build, test, artifact creation, and controlled deployment for a portfolio project.",
                            LearningPriority = "High",
                            SkillId = 28,
                            Title = "Build a CI/CD pipeline"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Cache an expensive read path, choose an expiration strategy, handle invalidation, and measure the performance change.",
                            LearningPriority = "Medium",
                            SkillId = 29,
                            Title = "Add Redis caching"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Use RabbitMQ to publish and consume durable messages with acknowledgements, retries, and idempotent handlers.",
                            LearningPriority = "Medium",
                            SkillId = 30,
                            Title = "Build an event-driven workflow"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Practice the CLI, project structure, configuration, dependency injection, async code, testing, and deployment.",
                            LearningPriority = "High",
                            SkillId = 31,
                            Title = "Strengthen the .NET platform basics"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Practice routing, server and client components, data fetching, metadata, loading states, and deployment.",
                            LearningPriority = "Medium",
                            SkillId = 32,
                            Title = "Build a Next.js page"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Create reusable responsive components with consistent spacing, typography, colors, states, and accessibility.",
                            LearningPriority = "Low",
                            SkillId = 33,
                            Title = "Build a Tailwind design system"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Practice schemas, queries, mutations, validation, resolver performance, authorization, and avoiding N+1 queries.",
                            LearningPriority = "Medium",
                            SkillId = 34,
                            Title = "Design a GraphQL API"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Use the shell, permissions, processes, services, logs, networking tools, and environment variables on a small server.",
                            LearningPriority = "Medium",
                            SkillId = 35,
                            Title = "Practice Linux for development"
                        });
                });

            modelBuilder.Entity("SkillMatch.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Job", b =>
                {
                    b.HasOne("SkillMatch.API.Models.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatch", b =>
                {
                    b.HasOne("SkillMatch.API.Models.Job", "Job")
                        .WithMany("JobMatches")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.Resume", "Resume")
                        .WithMany("JobMatches")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.User", "User")
                        .WithMany("JobMatches")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Resume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatchSkill", b =>
                {
                    b.HasOne("SkillMatch.API.Models.JobMatch", "JobMatch")
                        .WithMany("MatchSkills")
                        .HasForeignKey("JobMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("JobMatchSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("JobMatch");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobSkill", b =>
                {
                    b.HasOne("SkillMatch.API.Models.Job", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Resume", b =>
                {
                    b.HasOne("SkillMatch.API.Models.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SkillMatch.API.Models.ResumeSkill", b =>
                {
                    b.HasOne("SkillMatch.API.Models.Resume", "Resume")
                        .WithMany("ResumeSkills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("ResumeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.SkillRecommendation", b =>
                {
                    b.HasOne("SkillMatch.API.Models.Skill", "Skill")
                        .WithMany("Recommendations")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Job", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.JobMatch", b =>
                {
                    b.Navigation("MatchSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Resume", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("ResumeSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.Skill", b =>
                {
                    b.Navigation("JobMatchSkills");

                    b.Navigation("JobSkills");

                    b.Navigation("Recommendations");

                    b.Navigation("ResumeSkills");
                });

            modelBuilder.Entity("SkillMatch.API.Models.User", b =>
                {
                    b.Navigation("JobMatches");

                    b.Navigation("Jobs");

                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
